name: Generate ISO image

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  geniso:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64]
        variant: [liveimage-desktop, liveimage-standard, tarball]
        exclude:
          - arch: riscv64
            variant: liveimage-desktop
        include:
          - arch: x86_64
            debarch: amd64
          - arch: aarch64
            debarch: arm64
          - arch: riscv64
            debarch: riscv64
    runs-on: ubuntu-24.04
    name: Generate ISO for ${{ matrix.variant }} - ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}
          image: 'tonistiigi/binfmt:qemu-v8.1.5'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget dosfstools arch-install-scripts sudo pacman-package-manager xorriso arch-install-scripts squashfs-tools systemd-container
      - name: Build ISO for ${{ matrix.variant }} - ${{ matrix.arch }}
        run: |
          ./gen.sh ${{ matrix.variant }} ${{ matrix.arch }}
      - name: Check build Results
        id: buildresult
        run: |
          ls results/ | grep -v .sha256
          ls results/ | grep .sha256
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eweos-${{ matrix.arch }}-${{ matrix.variant }}
          path: results/
          compression-level: 0
      - name: Create GitHub Release
        if: github.event_name != 'pull_request'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'continuous-${{ github.run_id }}-${{ matrix.arch }}-${{ matrix.variant }}'
          release_name: 'Continuous Release ${{ github.run_id }} - ${{ matrix.arch }} - ${{ matrix.variant }}'
          draft: false
          prerelease: true
          body: "Automated continuous release for ${{ matrix.variant }} on ${{ matrix.arch }} architecture."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to GitHub Release
        if: github.event_name != 'pull_request'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: results/
          asset_name: eweos-${{ matrix.arch }}-${{ matrix.variant }}.iso
          asset_content_type: application/octet-stream
